name: inframaptraining
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - gdal=3.3.3
  - geopandas=0.13.2
  - numpy=1.23.2
  - openpyxl=3.1.2
  - pandas=2.2.1
  - pandana=0.6.1
  - plotly=5.10.0
  - pycountry=22.3.5
  - pip=23.3.2
  - flake8=7.0.0 
  - autopep8=2.0.4 
  - pytest==7.4.0
  - pytest-cov==4.1.0
  - seaborn==0.13.2
  - pip:
    - osmnx==1.7.0
    - rustworkx==0.15.1
    - ipykernel==6.25.0
    - jupyterlab==4.1.1
    - rasterio==1.3.8
    - tqdm==4.66.5
    - sqlalchemy==2.0.32
    - psycopg2==2.9.9
    - scikit_learn==1.1.2
    - scipy==1.9.1
    - shapely==2.0.2
    - python-srtm==0.5.0
    - pyyaml==6.0.1
    - python-dotenv==1.0.1
    - contextily==1.6.2
    - summarytools==0.3.0
    - fastparquet==2024.5.0
    - s3fs==2024.10.0
    - ipywidgets==8.1.5