name: inframaptraining
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - geopandas
  - matplotlib
  - numpy>=1.21.0
  - flake8
  - autopep8
  - pandas
  - rasterio
  - rasterstats=0.19.0
  - scipy
  - folium
  - shapely
  - osmnx
  - nbconvert
  - ipykernel
  - contextily=1.6.2
  - python-dotenv==1.0.1
  - pip
  - pip:
    - ipywidgets
    - pycountry==24.6.1
    - python-srtm==0.5.0